server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

