spring:
  application:
    name: pedido-ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food-pedido?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
server:
  port: 0